function [t ntots n xrays] = calc_xray_dn_sub(params, sol, tMax)
n0xs = [params.ndn10 * (1-params.pdn1); ...
    params.ndn20 * (1-params.pdn2); ...
    params.ndn30 * (1-params.pdn3); ...
    params.ndn40 * (1-params.pdn4); ...
    params.nctec0 * (1-params.pctec); ...
    params.ndp0 * (1-params.pdp) ...
];
omegas = [params.omegadn1 params.omegadn2 params.omegadn3 params.omegadn4 params.omegactec params.omegadp];
t = linspace(0, tMax,1000);
n = deval(sol,t);
xrays = n0xs .* exp(-omegas' * t);
ntots = n + xrays;

end