function S = dde_history_coarse_grained(t, params)
S = [params.ndn_0   * (params.p_dn   + (1-params.p_dn)   * (t<0)); ...
     params.ndp_0   * (params.p_dp   + (1-params.p_dp)   * (t<0)); ...
     params.nctec_0 * (params.p_ctec + (1-params.p_ctec) * (t<0)); ...
     params.nsp4_0  * (params.p_sp4  + (1-params.p_sp4)  * (t<0)); ...
     params.nmtec_0 * (params.p_mtec + (1-params.p_mtec) * (t<0))];
end