function S = dde_history_dn_sub(t, params)
S = [...
    params.ndn10* (params.pdn1 + (1-params.pdn1) * (t<0)); ...
    params.ndn20* (params.pdn2 + (1-params.pdn2) * (t<0)); ...
    params.ndn30* (params.pdn3 + (1-params.pdn3) * (t<0)); ...
    params.ndn40* (params.pdn4 + (1-params.pdn4) * (t<0)); ...
    params.nctec0* (params.pctec + (1-params.pctec) * (t<0)); ...
    params.ndp0* (params.pdp + (1-params.pdp) * (t<0)); ...      
];
end